Disable `main` branch of Android snapshots as regressed (#336)
Most probably regressed in `swift-DEVELOPMENT-SNAPSHOT-2026-04-01-a`

```
/usr/local/lib/android/sdk/ndk/29.0.14206865/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/threads.h:38:10: error: could not build module 'pthread'
 36 | #include <sys/cdefs.h>
 37 | 
 38 | #include <pthread.h>
    |          `- error: could not build module 'pthread'
 39 | #include <time.h>
 40 | 
```

Filed upstream as https://github.com/swiftlang/swift/issues/88443